/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatList: typeof import('./src/components/ChatList.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
